# Generated by Django 5.1.4 on 2024-12-31 23:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("advertisements", "0001_initial"),
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="advertisement",
            name="media",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ads_media",
                to="content.media",
                verbose_name="Ad Media",
            ),
        ),
        migrations.AddField(
            model_name="advertisement",
            name="placement",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ads_placement",
                to="advertisements.adplacement",
                verbose_name="Placement",
            ),
        ),
        migrations.AddField(
            model_name="adperformance",
            name="advertisement",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ads_performance",
                to="advertisements.advertisement",
                verbose_name="Advertisement",
            ),
        ),
        migrations.AddField(
            model_name="adcampaign",
            name="advertiser",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ad_campaigns",
                to="advertisements.advertiser",
                verbose_name="Advertiser",
            ),
        ),
    ]
