# Generated by Django 5.1.4 on 2026-09-14 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("advertisements", "0002_initial"),
        ("content", "0003_switch_tags_to_taggit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="advertisement",
            name="media",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ads_media",
                to="content.media",
                verbose_name="Ad Media",
            ),
        ),
        migrations.AlterField(
            model_name="advertisement",
            name="placement",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ads_placement",
                to="advertisements.adplacement",
                verbose_name="Placement",
            ),
        ),
    ]
