# Generated by Django 5.1.4 on 2026-09-15 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("advertisements", "0003_optional_placement_and_media"),
        ("content", "0006_magazine_pdf_rendered"),
    ]

    operations = [
        migrations.CreateModel(
            name="MediaKit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                ("title", models.CharField(default="Media kit", max_length=120)),
                ("file", models.FileField(upload_to="advertising/media-kit/")),
                ("year", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Media kit",
                "verbose_name_plural": "Media kits",
                "ordering": ["-year", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RateCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("print", "Print"),
                            ("digital", "Digital"),
                            ("social", "Social"),
                            ("bundle", "Bundle"),
                        ],
                        default="print",
                        max_length=12,
                        verbose_name="Channel",
                    ),
                ),
                ("slug", models.SlugField(max_length=80, unique=True)),
                (
                    "name_de",
                    models.CharField(max_length=120, verbose_name="Name (Deutsch)"),
                ),
                (
                    "name_ar",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Name (العربية)"
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Name (English)"
                    ),
                ),
                (
                    "description_de",
                    models.TextField(blank=True, verbose_name="Description (Deutsch)"),
                ),
                (
                    "description_ar",
                    models.TextField(blank=True, verbose_name="Description (العربية)"),
                ),
                (
                    "description_en",
                    models.TextField(blank=True, verbose_name="Description (English)"),
                ),
                (
                    "specs",
                    models.CharField(
                        blank=True,
                        help_text="e.g. 210 × 297 mm + 3 mm bleed, CMYK",
                        max_length=160,
                        verbose_name="Specification",
                    ),
                ),
                (
                    "width",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Width in mm (print) or px (digital), for the size preview.",
                        null=True,
                    ),
                ),
                (
                    "height",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Height in mm (print) or px (digital).",
                        null=True,
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=9, verbose_name="Price"
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("edition", "per edition"),
                            ("week", "per week"),
                            ("month", "per month"),
                            ("send", "per send"),
                            ("package", "per package"),
                        ],
                        default="edition",
                        max_length=12,
                        verbose_name="Billed",
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False, verbose_name="Highlight on the rate card"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Rate card entry",
                "verbose_name_plural": "Rate card",
                "ordering": ["channel", "order", "price"],
            },
        ),
        migrations.CreateModel(
            name="CampaignRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                ("company", models.CharField(max_length=160, verbose_name="Company")),
                (
                    "contact_name",
                    models.CharField(max_length=160, verbose_name="Contact"),
                ),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=40)),
                ("message", models.TextField(blank=True)),
                (
                    "estimate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Estimate shown",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("contacted", "Contacted"),
                            ("quoted", "Quoted"),
                            ("won", "Won"),
                            ("lost", "Lost"),
                        ],
                        default="new",
                        max_length=12,
                    ),
                ),
                ("language", models.CharField(blank=True, max_length=5)),
                (
                    "editions",
                    models.ManyToManyField(
                        blank=True,
                        related_name="campaign_requests",
                        to="content.magazine",
                    ),
                ),
            ],
            options={
                "verbose_name": "Campaign request",
                "verbose_name_plural": "Campaign requests",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CampaignRequestItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveSmallIntegerField(default=1)),
                (
                    "unit_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=9),
                ),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="advertisements.campaignrequest",
                    ),
                ),
                (
                    "rate_card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="request_items",
                        to="advertisements.ratecard",
                    ),
                ),
            ],
            options={
                "verbose_name": "Requested placement",
                "verbose_name_plural": "Requested placements",
            },
        ),
    ]
