# Generated by Django 5.1.4 on 2026-09-15 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("advertisements", "0004_mediakit_ratecard_campaignrequest_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mediakit",
            name="file",
            field=models.FileField(
                upload_to="advertising/media-kit/", verbose_name="File"
            ),
        ),
        migrations.AlterField(
            model_name="mediakit",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Shown on the site"),
        ),
        migrations.AlterField(
            model_name="mediakit",
            name="title",
            field=models.CharField(
                default="Media kit", max_length=120, verbose_name="Title"
            ),
        ),
        migrations.AlterField(
            model_name="mediakit",
            name="year",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="Year"
            ),
        ),
        migrations.AlterField(
            model_name="ratecard",
            name="description_ar",
            field=models.TextField(blank=True, verbose_name="Description (Arabic)"),
        ),
        migrations.AlterField(
            model_name="ratecard",
            name="description_de",
            field=models.TextField(blank=True, verbose_name="Description (German)"),
        ),
        migrations.AlterField(
            model_name="ratecard",
            name="height",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Height in mm (print) or px (digital).",
                null=True,
                verbose_name="Height",
            ),
        ),
        migrations.AlterField(
            model_name="ratecard",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Shown on the site"),
        ),
        migrations.AlterField(
            model_name="ratecard",
            name="name_ar",
            field=models.CharField(
                blank=True, max_length=120, verbose_name="Name (Arabic)"
            ),
        ),
        migrations.AlterField(
            model_name="ratecard",
            name="name_de",
            field=models.CharField(max_length=120, verbose_name="Name (German)"),
        ),
        migrations.AlterField(
            model_name="ratecard",
            name="order",
            field=models.PositiveSmallIntegerField(default=0, verbose_name="Order"),
        ),
        migrations.AlterField(
            model_name="ratecard",
            name="slug",
            field=models.SlugField(max_length=80, unique=True, verbose_name="Slug"),
        ),
        migrations.AlterField(
            model_name="ratecard",
            name="width",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Width in mm (print) or px (digital), for the size preview.",
                null=True,
                verbose_name="Width",
            ),
        ),
    ]
