# Generated by Django 5.1.4 on 2026-09-14 08:39

import source.apps.users.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "User", "verbose_name_plural": "Users"},
        ),
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", source.apps.users.managers.UserManager()),
            ],
        ),
    ]
