# Generated by Django 5.1.4 on 2026-09-15 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seo_analytics", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pagevisit",
            name="url",
            field=models.URLField(db_index=True, verbose_name="Visited URL"),
        ),
        migrations.AlterField(
            model_name="pagevisit",
            name="visit_date",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, verbose_name="Visit Date"
            ),
        ),
    ]
