# Generated by Django 5.1.4 on 2024-12-31 23:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("subscriptions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subscriptions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
        migrations.AddField(
            model_name="billing",
            name="subscription",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="billings",
                to="subscriptions.subscription",
                verbose_name="Subscription",
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="plan",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="subscriptions",
                to="subscriptions.subscriptionplan",
                verbose_name="Plan",
            ),
        ),
        migrations.AddField(
            model_name="featureaccess",
            name="plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feature_access",
                to="subscriptions.subscriptionplan",
                verbose_name="Plan",
            ),
        ),
        migrations.AddField(
            model_name="discountcode",
            name="plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="discounts",
                to="subscriptions.subscriptionplan",
                verbose_name="Plan",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="featureaccess",
            unique_together={("plan", "feature_name")},
        ),
    ]
