# Generated by Django 5.1.4 on 2024-12-31 23:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("content", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="author",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="article_author",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Author",
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="categories",
            field=models.ManyToManyField(
                related_name="article_categories",
                to="content.category",
                verbose_name="Categories",
            ),
        ),
        migrations.AddField(
            model_name="magazine",
            name="articles",
            field=models.ManyToManyField(
                related_name="magazine_articles",
                to="content.article",
                verbose_name="Articles",
            ),
        ),
        migrations.AddField(
            model_name="magazine",
            name="cover_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="magazine_covers",
                to="content.media",
                verbose_name="Cover Image",
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="media",
            field=models.ManyToManyField(
                blank=True,
                related_name="article_media",
                to="content.media",
                verbose_name="Media Attachments",
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                related_name="article_tags",
                to="content.tag",
                verbose_name="Tags",
            ),
        ),
    ]
