# Generated by Django 5.1.4 on 2026-09-15 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0003_switch_tags_to_taggit"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="is_sponsored",
            field=models.BooleanField(default=False, verbose_name="Sponsored content"),
        ),
        migrations.AddField(
            model_name="article",
            name="sponsor_name",
            field=models.CharField(blank=True, max_length=120, verbose_name="Sponsor"),
        ),
        migrations.AddField(
            model_name="magazine",
            name="issue_number",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Issue number"
            ),
        ),
        migrations.AddField(
            model_name="magazine",
            name="pdf",
            field=models.FileField(
                blank=True, upload_to="magazines/pdf/", verbose_name="Edition PDF"
            ),
        ),
    ]
