# Generated by Django 5.1.4 on 2026-09-15 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0004_article_is_sponsored_article_sponsor_name_and_more"),
        ("studio", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="magazine",
            name="theme",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="magazines",
                to="studio.theme",
                verbose_name="Theme",
            ),
        ),
    ]
