# Generated by Django 5.1.4 on 2026-09-15 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0005_magazine_theme"),
    ]

    operations = [
        migrations.AddField(
            model_name="magazine",
            name="pdf_rendered",
            field=models.CharField(
                blank=True, editable=False, max_length=255, verbose_name="Rendered PDF"
            ),
        ),
    ]
