# Generated by Django 5.1.4 on 2026-09-15 13:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0006_magazine_pdf_rendered"),
    ]

    operations = [
        migrations.AddField(
            model_name="media",
            name="caption",
            field=models.CharField(blank=True, max_length=255, verbose_name="Caption"),
        ),
        migrations.AddField(
            model_name="media",
            name="credit",
            field=models.CharField(blank=True, max_length=160, verbose_name="Credit"),
        ),
        migrations.AddField(
            model_name="media",
            name="focal_x",
            field=models.FloatField(
                default=0.5,
                help_text="0 is the left edge, 1 the right. Crops keep this point in view.",
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(1.0),
                ],
                verbose_name="Focal point across",
            ),
        ),
        migrations.AddField(
            model_name="media",
            name="focal_y",
            field=models.FloatField(
                default=0.5,
                help_text="0 is the top edge, 1 the bottom.",
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(1.0),
                ],
                verbose_name="Focal point down",
            ),
        ),
        migrations.AddField(
            model_name="media",
            name="height",
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="media",
            name="width",
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
    ]
