# Generated by Django 5.1.4 on 2026-09-15 14:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0008_editorial_workflow"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["order", "name"],
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.AddField(
            model_name="category",
            name="accent",
            field=models.CharField(
                blank=True,
                help_text="Optional, e.g. #f2b25c. Colours the hub header.",
                max_length=7,
                verbose_name="Accent colour",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="intro_ar",
            field=models.TextField(blank=True, verbose_name="Intro (Arabic)"),
        ),
        migrations.AddField(
            model_name="category",
            name="intro_de",
            field=models.TextField(blank=True, verbose_name="Intro (German)"),
        ),
        migrations.AddField(
            model_name="category",
            name="intro_en",
            field=models.TextField(blank=True, verbose_name="Intro (English)"),
        ),
        migrations.AddField(
            model_name="category",
            name="name_ar",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Name (Arabic)"
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="name_de",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Name (German)"
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="name_en",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Name (English)"
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="order",
            field=models.PositiveIntegerField(default=0, verbose_name="Order"),
        ),
        migrations.CreateModel(
            name="Contributor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                ("name", models.CharField(max_length=160, verbose_name="Name")),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=160, unique=True, verbose_name="Slug"
                    ),
                ),
                (
                    "role_de",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Role (German)"
                    ),
                ),
                (
                    "role_ar",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Role (Arabic)"
                    ),
                ),
                (
                    "role_en",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Role (English)"
                    ),
                ),
                ("bio_de", models.TextField(blank=True, verbose_name="Bio (German)")),
                ("bio_ar", models.TextField(blank=True, verbose_name="Bio (Arabic)")),
                ("bio_en", models.TextField(blank=True, verbose_name="Bio (English)")),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Public e-mail"
                    ),
                ),
                ("website", models.URLField(blank=True, verbose_name="Website")),
                (
                    "social_handle",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Social handle"
                    ),
                ),
                ("social_url", models.URLField(blank=True, verbose_name="Social link")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Shown on the site"),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Order")),
                (
                    "portrait",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contributor_portraits",
                        to="content.media",
                        verbose_name="Portrait",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        help_text="Optional. Links the page to the articles this person wrote.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contributor",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Account",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contributor",
                "verbose_name_plural": "Contributors",
                "ordering": ["order", "name"],
            },
        ),
    ]
