# Generated by Django 5.1.4 on 2026-09-15 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0009_alter_category_options_category_accent_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="content_ar",
            field=models.TextField(blank=True, verbose_name="Text (Arabic)"),
        ),
        migrations.AddField(
            model_name="article",
            name="content_de",
            field=models.TextField(blank=True, verbose_name="Text (German)"),
        ),
        migrations.AddField(
            model_name="article",
            name="content_en",
            field=models.TextField(blank=True, verbose_name="Text (English)"),
        ),
        migrations.AddField(
            model_name="article",
            name="standfirst_ar",
            field=models.TextField(blank=True, verbose_name="Standfirst (Arabic)"),
        ),
        migrations.AddField(
            model_name="article",
            name="standfirst_de",
            field=models.TextField(
                blank=True,
                help_text="The line under the headline. Leave empty to take the opening of the text.",
                verbose_name="Standfirst (German)",
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="standfirst_en",
            field=models.TextField(blank=True, verbose_name="Standfirst (English)"),
        ),
        migrations.AddField(
            model_name="article",
            name="title_ar",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Title (Arabic)"
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="title_de",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Title (German)"
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="title_en",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Title (English)"
            ),
        ),
    ]
