# Generated by Django 5.1.4 on 2026-09-14 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("archives", "0001_initial"),
        ("content", "0003_switch_tags_to_taggit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="edition",
            name="cover_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="edition_covers",
                to="content.media",
                verbose_name="Edition Cover",
            ),
        ),
    ]
