# Generated by Django 5.1.4 on 2026-09-15 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("content", "0004_article_is_sponsored_article_sponsor_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "key",
                    models.SlugField(
                        help_text="Where it renders, e.g. home-leaderboard, article-rectangle.",
                        max_length=60,
                    ),
                ),
                (
                    "format",
                    models.CharField(
                        choices=[
                            ("leaderboard", "Leaderboard · 728×90"),
                            ("billboard", "Billboard · 970×250"),
                            ("rectangle", "Rectangle · 300×250"),
                            ("skyscraper", "Skyscraper · 300×600"),
                            ("mobile", "Mobile banner · 320×100"),
                        ],
                        default="leaderboard",
                        max_length=20,
                    ),
                ),
                ("advertiser", models.CharField(blank=True, max_length=120)),
                ("image", models.ImageField(upload_to="studio/ads/")),
                ("url", models.URLField(blank=True)),
                ("alt_text", models.CharField(blank=True, max_length=200)),
                ("is_active", models.BooleanField(default=True)),
                ("starts_at", models.DateTimeField(blank=True, null=True)),
                ("ends_at", models.DateTimeField(blank=True, null=True)),
                (
                    "weight",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="Higher wins when several bookings share a key.",
                    ),
                ),
            ],
            options={
                "ordering": ["key", "-weight"],
            },
        ),
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("editorial", "Editorial"),
                            ("ad", "Advertising"),
                            ("live", "Live"),
                        ],
                        default="editorial",
                        max_length=12,
                    ),
                ),
                ("text_de", models.CharField(max_length=160)),
                ("text_ar", models.CharField(blank=True, max_length=160)),
                ("text_en", models.CharField(blank=True, max_length=160)),
                ("url", models.CharField(blank=True, max_length=300)),
                ("is_active", models.BooleanField(default=True)),
                ("starts_at", models.DateTimeField(blank=True, null=True)),
                ("ends_at", models.DateTimeField(blank=True, null=True)),
                ("order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "ordering": ["order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "page",
                    models.CharField(
                        choices=[
                            ("help", "Help"),
                            ("advertise", "Advertising"),
                            ("about", "About"),
                        ],
                        default="help",
                        max_length=20,
                    ),
                ),
                ("question_de", models.CharField(max_length=200)),
                ("question_ar", models.CharField(blank=True, max_length=200)),
                ("question_en", models.CharField(blank=True, max_length=200)),
                ("answer_de", models.TextField()),
                ("answer_ar", models.TextField(blank=True)),
                ("answer_en", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "verbose_name": "FAQ",
                "verbose_name_plural": "FAQ",
                "ordering": ["page", "order"],
            },
        ),
        migrations.CreateModel(
            name="Milestone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                ("year", models.PositiveSmallIntegerField()),
                ("title_de", models.CharField(max_length=120)),
                ("title_ar", models.CharField(blank=True, max_length=120)),
                ("title_en", models.CharField(blank=True, max_length=120)),
                ("text_de", models.TextField(blank=True)),
                ("text_ar", models.TextField(blank=True)),
                ("text_en", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["year"],
            },
        ),
        migrations.CreateModel(
            name="Partner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                ("name", models.CharField(max_length=120)),
                ("logo", models.ImageField(upload_to="studio/partners/")),
                ("url", models.URLField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                ("quote_de", models.TextField()),
                ("quote_ar", models.TextField(blank=True)),
                ("quote_en", models.TextField(blank=True)),
                ("name", models.CharField(max_length=120)),
                (
                    "role",
                    models.CharField(
                        blank=True, help_text="Role and company", max_length=160
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(blank=True, upload_to="studio/testimonials/"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "ordering": ["order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Theme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                ("name", models.CharField(max_length=80)),
                ("slug", models.SlugField(max_length=80, unique=True)),
                (
                    "accent",
                    models.CharField(
                        default="#f2b25c",
                        help_text="Highlight colour, e.g. gold.",
                        max_length=7,
                    ),
                ),
                (
                    "brand",
                    models.CharField(
                        default="#062a4a",
                        help_text="Brand surface colour, e.g. navy.",
                        max_length=7,
                    ),
                ),
                ("brand_deep", models.CharField(default="#031428", max_length=7)),
                (
                    "interaction",
                    models.CharField(
                        default="#0284c7", help_text="Links and buttons.", max_length=7
                    ),
                ),
                (
                    "display_font",
                    models.CharField(
                        choices=[
                            ("playfair", "Playfair Display"),
                            ("system-serif", "System serif"),
                            ("system-sans", "System sans"),
                        ],
                        default="playfair",
                        max_length=20,
                    ),
                ),
                (
                    "radius",
                    models.PositiveSmallIntegerField(
                        default=20,
                        help_text="Corner radius in px for cards and panels.",
                    ),
                ),
                ("is_default", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="HeroConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "placement",
                    models.SlugField(default="home", max_length=40, unique=True),
                ),
                (
                    "variant",
                    models.CharField(
                        choices=[
                            (
                                "front",
                                "Front page · masthead, glass text, book stack, ticker",
                            ),
                            ("light", "Light editorial · cream broadsheet, dark type"),
                            (
                                "immersive",
                                "Immersive · full-bleed photo, floating story cards",
                            ),
                            (
                                "newsroom",
                                "Newsroom · lead image, columns, edition sidebar",
                            ),
                            ("classic", "Classic · logos, director, edition slider"),
                        ],
                        default="front",
                        max_length=20,
                    ),
                ),
                ("background", models.ImageField(blank=True, upload_to="studio/hero/")),
                ("show_masthead", models.BooleanField(default=True)),
                ("show_stats", models.BooleanField(default=True)),
                ("show_ticker", models.BooleanField(default=True)),
                ("show_partners", models.BooleanField(default=False)),
                ("show_issue_facts", models.BooleanField(default=True)),
                ("kicker_de", models.CharField(blank=True, max_length=120)),
                ("kicker_ar", models.CharField(blank=True, max_length=120)),
                ("kicker_en", models.CharField(blank=True, max_length=120)),
                (
                    "headline_de",
                    models.CharField(
                        blank=True,
                        help_text="Wrap a word in *asterisks* to colour it.",
                        max_length=200,
                    ),
                ),
                ("headline_ar", models.CharField(blank=True, max_length=200)),
                ("headline_en", models.CharField(blank=True, max_length=200)),
                ("dek_de", models.TextField(blank=True)),
                ("dek_ar", models.TextField(blank=True)),
                ("dek_en", models.TextField(blank=True)),
                ("primary_label_de", models.CharField(blank=True, max_length=60)),
                ("primary_label_ar", models.CharField(blank=True, max_length=60)),
                ("primary_label_en", models.CharField(blank=True, max_length=60)),
                (
                    "primary_url",
                    models.CharField(
                        blank=True,
                        help_text="Leave empty to link the latest edition.",
                        max_length=200,
                    ),
                ),
                ("secondary_label_de", models.CharField(blank=True, max_length=60)),
                ("secondary_label_ar", models.CharField(blank=True, max_length=60)),
                ("secondary_label_en", models.CharField(blank=True, max_length=60)),
                (
                    "secondary_url",
                    models.CharField(
                        blank=True,
                        help_text="Leave empty to link the advertising page.",
                        max_length=200,
                    ),
                ),
                (
                    "pages_label",
                    models.CharField(
                        blank=True, help_text="e.g. 96 pages", max_length=40
                    ),
                ),
                (
                    "price_label",
                    models.CharField(
                        blank=True, help_text="e.g. 4,90 € · free online", max_length=40
                    ),
                ),
                (
                    "theme",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="studio.theme",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hero",
                "verbose_name_plural": "Heroes",
            },
        ),
        migrations.CreateModel(
            name="MagazinePage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.PositiveIntegerField()),
                ("image", models.ImageField(upload_to="magazines/pages/")),
                (
                    "thumbnail",
                    models.ImageField(blank=True, upload_to="magazines/thumbs/"),
                ),
                ("width", models.PositiveIntegerField(default=0)),
                ("height", models.PositiveIntegerField(default=0)),
                (
                    "magazine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pages",
                        to="content.magazine",
                    ),
                ),
            ],
            options={
                "ordering": ["magazine", "number"],
                "unique_together": {("magazine", "number")},
            },
        ),
    ]
