# Generated by Django 5.1.4 on 2026-09-15 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studio", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PressKit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "name",
                    models.CharField(
                        default="Press kit", max_length=120, verbose_name="Name"
                    ),
                ),
                (
                    "is_current",
                    models.BooleanField(default=True, verbose_name="In force"),
                ),
                (
                    "boilerplate_de",
                    models.TextField(
                        blank=True,
                        help_text="The paragraph a journalist may quote about the magazine.",
                        verbose_name="Boilerplate (German)",
                    ),
                ),
                (
                    "boilerplate_ar",
                    models.TextField(blank=True, verbose_name="Boilerplate (Arabic)"),
                ),
                (
                    "boilerplate_en",
                    models.TextField(blank=True, verbose_name="Boilerplate (English)"),
                ),
                (
                    "contact_name",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Press contact"
                    ),
                ),
                (
                    "contact_role_de",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Role (German)"
                    ),
                ),
                (
                    "contact_role_ar",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Role (Arabic)"
                    ),
                ),
                (
                    "contact_role_en",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Role (English)"
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Press e-mail"
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(
                        blank=True, max_length=40, verbose_name="Press phone"
                    ),
                ),
                (
                    "archive",
                    models.FileField(
                        blank=True,
                        help_text="Optional zip with the logos and the boilerplate.",
                        upload_to="press/",
                        verbose_name="Everything as one download",
                    ),
                ),
            ],
            options={
                "verbose_name": "Press kit",
                "verbose_name_plural": "Press kits",
                "ordering": ["-is_current", "-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="PressAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                ("label", models.CharField(max_length=120, verbose_name="Label")),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("logo", "Logo"),
                            ("logo-mono", "Logo, one colour"),
                            ("cover", "Cover"),
                            ("portrait", "Portrait"),
                            ("photo", "Photograph"),
                        ],
                        default="logo",
                        max_length=20,
                        verbose_name="Kind",
                    ),
                ),
                (
                    "background",
                    models.CharField(
                        choices=[
                            ("light", "For light backgrounds"),
                            ("dark", "For dark backgrounds"),
                        ],
                        default="light",
                        max_length=10,
                        verbose_name="Shown on",
                    ),
                ),
                (
                    "file",
                    models.FileField(upload_to="press/assets/", verbose_name="File"),
                ),
                (
                    "preview",
                    models.ImageField(
                        blank=True,
                        help_text="Optional. Needed when the file itself is not a web image, e.g. an EPS.",
                        upload_to="press/previews/",
                        verbose_name="Preview",
                    ),
                ),
                (
                    "credit",
                    models.CharField(blank=True, max_length=160, verbose_name="Credit"),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Order"),
                ),
                (
                    "kit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assets",
                        to="studio.presskit",
                        verbose_name="Press kit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Press asset",
                "verbose_name_plural": "Press assets",
                "ordering": ["order", "label"],
            },
        ),
    ]
