# Generated by Django 5.1.4 on 2026-09-15 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studio", "0002_presskit_pressasset"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adslot",
            name="advertiser",
            field=models.CharField(
                blank=True, max_length=120, verbose_name="Advertiser"
            ),
        ),
        migrations.AlterField(
            model_name="adslot",
            name="alt_text",
            field=models.CharField(blank=True, max_length=200, verbose_name="Alt text"),
        ),
        migrations.AlterField(
            model_name="adslot",
            name="ends_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Runs until"
            ),
        ),
        migrations.AlterField(
            model_name="adslot",
            name="format",
            field=models.CharField(
                choices=[
                    ("leaderboard", "Leaderboard · 728×90"),
                    ("billboard", "Billboard · 970×250"),
                    ("rectangle", "Rectangle · 300×250"),
                    ("skyscraper", "Skyscraper · 300×600"),
                    ("mobile", "Mobile banner · 320×100"),
                ],
                default="leaderboard",
                max_length=20,
                verbose_name="Format",
            ),
        ),
        migrations.AlterField(
            model_name="adslot",
            name="image",
            field=models.ImageField(upload_to="studio/ads/", verbose_name="Image"),
        ),
        migrations.AlterField(
            model_name="adslot",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Shown on the site"),
        ),
        migrations.AlterField(
            model_name="adslot",
            name="key",
            field=models.SlugField(
                help_text="Where it renders, e.g. home-leaderboard, article-rectangle.",
                max_length=60,
                verbose_name="Placement key",
            ),
        ),
        migrations.AlterField(
            model_name="adslot",
            name="starts_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Runs from"),
        ),
        migrations.AlterField(
            model_name="adslot",
            name="url",
            field=models.URLField(blank=True, verbose_name="Link"),
        ),
        migrations.AlterField(
            model_name="adslot",
            name="weight",
            field=models.PositiveSmallIntegerField(
                default=1,
                help_text="Higher wins when several bookings share a key.",
                verbose_name="Weight",
            ),
        ),
        migrations.AlterField(
            model_name="faq",
            name="answer_ar",
            field=models.TextField(blank=True, verbose_name="Answer (Arabic)"),
        ),
        migrations.AlterField(
            model_name="faq",
            name="answer_de",
            field=models.TextField(verbose_name="Answer (German)"),
        ),
        migrations.AlterField(
            model_name="faq",
            name="answer_en",
            field=models.TextField(blank=True, verbose_name="Answer (English)"),
        ),
        migrations.AlterField(
            model_name="faq",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Shown on the site"),
        ),
        migrations.AlterField(
            model_name="faq",
            name="order",
            field=models.PositiveSmallIntegerField(default=0, verbose_name="Order"),
        ),
        migrations.AlterField(
            model_name="faq",
            name="page",
            field=models.CharField(
                choices=[
                    ("help", "Help"),
                    ("advertise", "Advertising"),
                    ("about", "About"),
                ],
                default="help",
                max_length=20,
                verbose_name="Page",
            ),
        ),
        migrations.AlterField(
            model_name="faq",
            name="question_ar",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Question (Arabic)"
            ),
        ),
        migrations.AlterField(
            model_name="faq",
            name="question_de",
            field=models.CharField(max_length=200, verbose_name="Question (German)"),
        ),
        migrations.AlterField(
            model_name="faq",
            name="question_en",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Question (English)"
            ),
        ),
        migrations.AlterField(
            model_name="milestone",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Shown on the site"),
        ),
        migrations.AlterField(
            model_name="milestone",
            name="text_ar",
            field=models.TextField(blank=True, verbose_name="Text (Arabic)"),
        ),
        migrations.AlterField(
            model_name="milestone",
            name="text_de",
            field=models.TextField(blank=True, verbose_name="Text (German)"),
        ),
        migrations.AlterField(
            model_name="milestone",
            name="text_en",
            field=models.TextField(blank=True, verbose_name="Text (English)"),
        ),
        migrations.AlterField(
            model_name="milestone",
            name="title_ar",
            field=models.CharField(
                blank=True, max_length=120, verbose_name="Title (Arabic)"
            ),
        ),
        migrations.AlterField(
            model_name="milestone",
            name="title_de",
            field=models.CharField(max_length=120, verbose_name="Title (German)"),
        ),
        migrations.AlterField(
            model_name="milestone",
            name="title_en",
            field=models.CharField(
                blank=True, max_length=120, verbose_name="Title (English)"
            ),
        ),
        migrations.AlterField(
            model_name="milestone",
            name="year",
            field=models.PositiveSmallIntegerField(verbose_name="Year"),
        ),
        migrations.AlterField(
            model_name="partner",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Shown on the site"),
        ),
        migrations.AlterField(
            model_name="partner",
            name="logo",
            field=models.ImageField(upload_to="studio/partners/", verbose_name="Logo"),
        ),
        migrations.AlterField(
            model_name="partner",
            name="name",
            field=models.CharField(max_length=120, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="partner",
            name="order",
            field=models.PositiveSmallIntegerField(default=0, verbose_name="Order"),
        ),
        migrations.AlterField(
            model_name="partner",
            name="url",
            field=models.URLField(blank=True, verbose_name="Link"),
        ),
        migrations.AlterField(
            model_name="testimonial",
            name="avatar",
            field=models.ImageField(
                blank=True, upload_to="studio/testimonials/", verbose_name="Portrait"
            ),
        ),
        migrations.AlterField(
            model_name="testimonial",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Shown on the site"),
        ),
        migrations.AlterField(
            model_name="testimonial",
            name="name",
            field=models.CharField(max_length=120, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="testimonial",
            name="order",
            field=models.PositiveSmallIntegerField(default=0, verbose_name="Order"),
        ),
        migrations.AlterField(
            model_name="testimonial",
            name="quote_ar",
            field=models.TextField(blank=True, verbose_name="Quote (Arabic)"),
        ),
        migrations.AlterField(
            model_name="testimonial",
            name="quote_de",
            field=models.TextField(verbose_name="Quote (German)"),
        ),
        migrations.AlterField(
            model_name="testimonial",
            name="quote_en",
            field=models.TextField(blank=True, verbose_name="Quote (English)"),
        ),
        migrations.AlterField(
            model_name="testimonial",
            name="role",
            field=models.CharField(
                blank=True,
                help_text="Role and company",
                max_length=160,
                verbose_name="Role",
            ),
        ),
    ]
