# Generated by Django 5.1.4 on 2026-09-15 15:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("content", "0009_alter_category_options_category_accent_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("review", "In review"),
                            ("scheduled", "Scheduled"),
                            ("published", "Published"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=16,
                        verbose_name="Status",
                    ),
                ),
                (
                    "scheduled_for",
                    models.DateTimeField(
                        blank=True,
                        help_text="Leave empty to publish by hand.",
                        null=True,
                        verbose_name="Goes live",
                    ),
                ),
                (
                    "editor_note",
                    models.CharField(
                        blank=True,
                        help_text="What is still missing, for the desk only.",
                        max_length=255,
                        verbose_name="Desk note",
                    ),
                ),
                (
                    "preview_token",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Title")),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=255, unique=True, verbose_name="Slug"
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("launch", "Edition launch"),
                            ("panel", "Panel or talk"),
                            ("reading", "Reading"),
                            ("community", "Community event"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                        verbose_name="Kind",
                    ),
                ),
                (
                    "title_de",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Title (German)"
                    ),
                ),
                (
                    "title_ar",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Title (Arabic)"
                    ),
                ),
                (
                    "title_en",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Title (English)"
                    ),
                ),
                (
                    "summary_de",
                    models.TextField(blank=True, verbose_name="Summary (German)"),
                ),
                (
                    "summary_ar",
                    models.TextField(blank=True, verbose_name="Summary (Arabic)"),
                ),
                (
                    "summary_en",
                    models.TextField(blank=True, verbose_name="Summary (English)"),
                ),
                ("starts_at", models.DateTimeField(verbose_name="Starts")),
                (
                    "ends_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Leave empty for an open end.",
                        null=True,
                        verbose_name="Ends",
                    ),
                ),
                (
                    "venue",
                    models.CharField(blank=True, max_length=160, verbose_name="Venue"),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Address"
                    ),
                ),
                (
                    "city",
                    models.CharField(blank=True, max_length=120, verbose_name="City"),
                ),
                (
                    "is_online",
                    models.BooleanField(default=False, verbose_name="Online event"),
                ),
                (
                    "registration_url",
                    models.URLField(blank=True, verbose_name="Tickets or registration"),
                ),
                (
                    "is_free",
                    models.BooleanField(default=True, verbose_name="Free entry"),
                ),
                (
                    "price_note",
                    models.CharField(
                        blank=True,
                        help_text="e.g. 5 € at the door.",
                        max_length=120,
                        verbose_name="Price note",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="Is Published"),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Published At"
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="event_images",
                        to="content.media",
                        verbose_name="Picture",
                    ),
                ),
            ],
            options={
                "verbose_name": "Event",
                "verbose_name_plural": "Events",
                "ordering": ["-starts_at"],
            },
        ),
    ]
